services:
  postgres:
    image: postgres:17
    container_name: hireflow_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: hireflow
      POSTGRES_USER: hireflow
      POSTGRES_PASSWORD: hireflow_dev_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: